
#Миры в которых не будут работать функции плагина
blocked-worlds:
  - 'world_nether'
  - 'world_the_end'

thirst:

  #Указанное здесь время будет является интервалом
  #по которому будет уменьшаться значение жажды
  #Указывать в секундах
  change-rate: 15
  
  #Урон от жажды
  damage:
  
    #Интервал нанесения урона
    #Указывать в секундах
    rate: 3
    
    #Значение урона
    #У игрока максимум 20 жизней (1 значение = пол сердца)
    value: 4
  
  values:
  
    #Максимальные и минимальные значения жажды
    max: 100
    min: 0
    
  #Настройки боссбара
  bossbar:
  
    #Отображаемое название
    #API: <player> <thirst>
    title: '&fЖажда: &a<thirst>'
    
    #Цвет линии босбара
    color: 'blue'
    
  #Список предметов, восполняющие жажду
  #Указывать в формате:
  #<id предмета>: <значение жажды>
  #Пример:
  #POTION: 60
  items:
  
    potion: 60
    apple: 20
    melon: 40
  
#Здесь указаны сообщения
messages:
  
  #Предупреждения о малом значении жажды
  #Указывать в формате: 
  #<значение жажды>: '<сообщение>'
  #Пример:
  #10: 'Вы очень хотите пить!'
  #Если не нужны, то удалите эту секцию
  warnings:
    
    30: '&cУ вас умеренная жажда!'
    20: '&cУ вас небольшая жажда!'
    10: '&4У вас сильная жажда, выпейте воды!'
      
  #Выводится, если игрок пытается использовать
  #команду /corez (Доступна только OP)
  not-permission: '&cВы не имеете прав!'

health:

  #В майнкрафте при полном значении шкалы голода
  #у игрока восстанавливаются жизни
  #Если true, то эта функция будет отключена
  disable-autoregen: true
  
  #Предметы, восполняющие жизни
  #Указывать в формате:
  #<id предмета>: <жизни>
  #Пример:
  #GOLDEN_APPLE: 5
  #У игрока максимум 20 жизней (1 значение = пол сердца)
  items:
  
    apple: 1
    beef: 2
    grilled_pork: 3
    
zombie:

  #Если true, то функция спавна зомби будет включена
  enable: true
  
  #Интервал по которому зомби будут спавниться
  #Указывать в секундах
  spawn-rate: 30
  
  #Максимальное значение энтити вокруг игрока
  #Если значение будет больше, чем указано здесь,
  #то зомби спавниться не будут
  max-entities: 15
  
  #Модификации параметров зомби
  modifications:
  
    #Значение здоровья зомби
    #Стандартно: 20.0
    health: 20.0
    
    #Скорость зомби
    #Стандартно: 1
    speed: 1